export const DATABASE_MODULE_OPTIONS = 'DATABASE_MODULE_OPTIONS';
export const DATABASE_CONNECTIONS = 'DATABASE_CONNECTIONS';
export const DEFAULT_CONNECTION_NAME = 'default';
export const DATA_SOURCE_MANAGER = 'DATA_SOURCE_MANAGER';
